_target_: jepa.JEPA

pred_proj_type: mlp
pred_proj_hidden_dim: 2048
bottleneck_dim: 64
grid_size: 8
grid_min: -2.0
grid_max: 2.0
adaptive_grid: false
use_base_linear: true
sparse_lambda: 1e-5

encoder:
  _target_: stable_pretraining.backbone.utils.vit_hf
  size: tiny
  patch_size: 14
  image_size: ${img_size}
  pretrained: false
  use_mask_token: false

predictor:
  _target_: module.ARPredictor
  num_frames: ${history_size}
  input_dim: ${embed_dim}
  hidden_dim: ${embed_dim}
  output_dim: ${embed_dim}
  depth: 6
  heads: 16
  mlp_dim: 2048
  dim_head: 64
  dropout: 0.1
  emb_dropout: 0.0

action_encoder:
  _target_: module.Embedder
  input_dim: ???
  emb_dim: ${embed_dim}

projector:
  _target_: module.MLP
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: 2048
  norm_fn:
    _target_: torch.nn.BatchNorm1d
    _partial_: true

pred_proj:
  _target_: kan_module.build_pred_proj
  pred_proj_type: ${model.pred_proj_type}
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: ${model.pred_proj_hidden_dim}
  bottleneck_dim: ${model.bottleneck_dim}
  grid_size: ${model.grid_size}
  grid_min: ${model.grid_min}
  grid_max: ${model.grid_max}
  adaptive_grid: ${model.adaptive_grid}
  use_base_linear: ${model.use_base_linear}
  sparse_lambda: ${model.sparse_lambda}
